describe('RemoveFromCartFlow', () => {
    it('removing from cart works', () => {
        cy.visit('/')
        cy.intercept('GET', '**/games/*', { fixture: 'games.json' }).as('getGames')
        cy.contains('a', 'Action').click()
        cy.wait('@getGames')
        cy.location('pathname')
            .should('eq', '/category/action')
        cy.contains('button', 'Add to Cart').click()
        cy.contains('a', 'Cart').click()
        cy.location('pathname')
            .should('eq', '/cart')
        cy.contains('Hades')
        cy.contains('button', 'Remove').click()
        cy.contains('Your cart is empty')
    })
})